export type ApiMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

export interface ApiField {
  name: string
  type: string
  required?: boolean
  description: string
}

export interface ApiEndpoint {
  method: ApiMethod
  path: string
  title: string
  auth: string
  roles: string
  description: string
  params?: string[]
  body?: ApiField[]
  response?: string
  errors?: string[]
  managerScope?: string
}

export interface ApiSection {
  id: string
  title: string
  description: string
  endpoints: ApiEndpoint[]
}

const BASE = '/api/v1'

const AUTH_TOKEN = 'Bearer token (from login)'
const ANY_ROLE = 'Any authenticated active user'
const ADMIN_MANAGER = 'Admin or Manager'
const ADMIN_ONLY = 'Admin only'

const authErrors = ['401 — invalid credentials', '403 — account deactivated', '422 — validation failed', '429 — too many login attempts (5 per minute)']

export const API_SECTIONS: ApiSection[] = [
  {
    id: 'authentication',
    title: 'Authentication',
    description: 'Sign in, sign out, and inspect the current session. Login is the only public endpoint.',
    endpoints: [
      {
        method: 'POST',
        path: `${BASE}/auth/login`,
        title: 'Log in',
        auth: 'None (public, rate-limited)',
        roles: 'None',
        description: 'Authenticate with email and password and receive a Sanctum bearer token.',
        body: [
          { name: 'email', type: 'string', required: true, description: 'The user email address.' },
          { name: 'password', type: 'string', required: true, description: 'Password, at least 8 characters.' },
        ],
        response: `{
  "success": true,
  "data": {
    "token": "1|xxxxxxxxxxxxxxxxxxxxxxxx",
    "user": { "id": 1, "name": "...", "email": "...", "role": "admin", "is_active": true }
  },
  "message": "Login successful"
}`,
        errors: authErrors,
      },
      {
        method: 'POST',
        path: `${BASE}/auth/logout`,
        title: 'Log out',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Revoke the current access token.',
        response: '{ "success": true, "message": "Logged out successfully" }',
        errors: ['401 — missing or invalid token'],
      },
      {
        method: 'GET',
        path: `${BASE}/auth/me`,
        title: 'Current user',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Return the profile of the authenticated user.',
        response: `{
  "success": true,
  "data": { "id": 1, "name": "...", "email": "...", "role": "manager", "is_active": true }
}`,
        errors: ['401 — missing or invalid token'],
      },
    ],
  },
  {
    id: 'users',
    title: 'Users',
    description: 'User accounts. Only administrators can manage users. Roles are admin or manager.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/users`,
        title: 'List users',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Paginated list of users with search and role/status filters.',
        params: ['search — name or email', 'role — admin, manager', 'is_active / status — boolean', 'page, per_page (1–100)'],
        errors: ['401 — not authenticated', '403 — not an admin', '422 — invalid filter values'],
      },
      {
        method: 'POST',
        path: `${BASE}/users`,
        title: 'Create user',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Create a new admin or manager account.',
        body: [
          { name: 'name', type: 'string', required: true, description: 'Display name.' },
          { name: 'email', type: 'email', required: true, description: 'Must be unique.' },
          { name: 'password', type: 'string', required: true, description: 'Min 8 characters.' },
          { name: 'password_confirmation', type: 'string', required: true, description: 'Must match password.' },
          { name: 'role', type: 'string', required: true, description: 'admin or manager.' },
          { name: 'is_active', type: 'boolean', description: 'Defaults to true.' },
        ],
        errors: ['403 — not an admin', '422 — duplicate email or invalid role (staff is rejected)'],
      },
      {
        method: 'GET',
        path: `${BASE}/users/{id}`,
        title: 'Show user',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Return a single user.',
        errors: ['404 — not found'],
      },
      {
        method: 'PUT',
        path: `${BASE}/users/{id}`,
        title: 'Update user',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Update name, email, password, role, or active status.',
        body: [
          { name: 'name', type: 'string', description: 'Display name.' },
          { name: 'email', type: 'email', description: 'Must be unique.' },
          { name: 'password', type: 'string', description: 'Min 8 characters, optional on update.' },
          { name: 'role', type: 'string', description: 'admin or manager.' },
          { name: 'is_active', type: 'boolean', description: 'Activate or deactivate.' },
        ],
        errors: ['403 — not an admin', '422 — validation failed', '404 — not found'],
      },
      {
        method: 'DELETE',
        path: `${BASE}/users/{id}`,
        title: 'Delete user',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Delete a user. Deleting your own account is blocked.',
        errors: ['422 — cannot delete your own account', '403 — not an admin', '404 — not found'],
      },
      {
        method: 'PATCH',
        path: `${BASE}/users/{id}/toggle-status`,
        title: 'Toggle user status',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Activate or deactivate a user. Deactivated users cannot authenticate.',
        errors: ['422 — cannot deactivate your own account', '403 — not an admin'],
      },
    ],
  },
  {
    id: 'warehouses',
    title: 'Warehouses',
    description: 'Physical locations where stock is held. Managers see only their assigned warehouse.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/warehouses`,
        title: 'List warehouses',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated list. Managers only see their assigned warehouse. Pass ?status=archived to see archived ones.',
        params: ['search — name or location', 'status — archived', 'page, per_page (1–100)'],
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/warehouses/transfer-targets`,
        title: 'Transfer targets',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Active warehouses available as transfer destinations (id, name, location).',
      },
      {
        method: 'GET',
        path: `${BASE}/warehouses/{id}`,
        title: 'Show warehouse',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Warehouse details including inventory totals and inventory value.',
        params: ['id — numeric warehouse id'],
        managerScope: 'Managers can only view their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/warehouses/{id}/inventory`,
        title: 'Warehouse inventory',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated inventory rows for a warehouse, archived warehouses included.',
        params: ['id — numeric warehouse id', 'page, per_page (1–100)'],
        managerScope: 'Managers can only view their assigned warehouse.',
      },
      {
        method: 'POST',
        path: `${BASE}/warehouses`,
        title: 'Create warehouse',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Create a warehouse, optionally assigning a manager.',
        body: [
          { name: 'name', type: 'string', required: true, description: 'Unique among active warehouses.' },
          { name: 'location', type: 'string', required: true, description: 'Address or area.' },
          { name: 'description', type: 'string', description: 'Optional notes.' },
          { name: 'manager_id', type: 'number', description: 'A user with role manager, not already assigned.' },
        ],
        errors: ['403 — not an admin', '422 — manager already assigned to another warehouse'],
      },
      {
        method: 'PUT',
        path: `${BASE}/warehouses/{id}`,
        title: 'Update warehouse',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Update warehouse details. Archived warehouses cannot be edited.',
        errors: ['422 — archived warehouses cannot be edited', '422 — manager already assigned elsewhere'],
      },
      {
        method: 'POST',
        path: `${BASE}/warehouses/{id}/archive`,
        title: 'Archive warehouse',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Archive a warehouse. Blocked while it holds stock, if inactive, or if it is the last active warehouse.',
        errors: ['409 — cannot archive (holds stock / last active / already archived)'],
      },
      {
        method: 'POST',
        path: `${BASE}/warehouses/{id}/restore`,
        title: 'Restore warehouse',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Restore an archived warehouse. Name must not clash with another warehouse.',
        errors: ['409 — name conflict or not archived'],
      },
    ],
  },
  {
    id: 'products',
    title: 'Products',
    description: 'The catalog of items you buy and sell. Products carry SKU, prices, and stock hints.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/products`,
        title: 'List products',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated list with search and category, supplier, and status filters.',
        params: ['search — name or sku', 'category_id', 'supplier_id', 'status — active, inactive, discontinued', 'page, per_page (1–100)'],
      },
      {
        method: 'GET',
        path: `${BASE}/products/low-stock`,
        title: 'Low stock products',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Products whose stock is at or below their reorder point.',
      },
      {
        method: 'GET',
        path: `${BASE}/products/{id}`,
        title: 'Show product',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'A single product with its category and supplier.',
      },
      {
        method: 'POST',
        path: `${BASE}/products`,
        title: 'Create product',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Create a product. SKU must be unique.',
        body: [
          { name: 'category_id', type: 'number', required: true, description: 'Existing category id.' },
          { name: 'sku', type: 'string', required: true, description: 'Unique SKU.' },
          { name: 'name', type: 'string', required: true, description: 'Product name.' },
          { name: 'unit_price', type: 'number', required: true, description: 'Selling price (min 0).' },
          { name: 'cost_price', type: 'number', required: true, description: 'Purchase cost (min 0).' },
          { name: 'supplier_id', type: 'number', description: 'Preferred supplier.' },
          { name: 'description', type: 'string', description: 'Optional.' },
          { name: 'unit', type: 'string', description: 'e.g. pcs, kg.' },
          { name: 'status', type: 'string', description: 'active, inactive, or discontinued.' },
        ],
        errors: ['422 — duplicate SKU or invalid category'],
      },
      {
        method: 'PUT',
        path: `${BASE}/products/{id}`,
        title: 'Update product',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Update product fields. SKU uniqueness ignores the current product.',
        errors: ['422 — validation failed'],
      },
      {
        method: 'DELETE',
        path: `${BASE}/products/{id}`,
        title: 'Delete product',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Soft-delete (archive) a product. History is kept; archived products cannot be used in new operations.',
        errors: ['403 — not an admin', '409 — hard delete blocked when history exists'],
      },
    ],
  },
  {
    id: 'categories',
    title: 'Categories',
    description: 'Group products into categories for organization and filtering.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/categories`,
        title: 'List categories',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated categories with search and status filters.',
      },
      {
        method: 'GET',
        path: `${BASE}/categories/all`,
        title: 'All active categories',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Unpaginated list of active categories, ordered by name (used in forms).',
      },
      {
        method: 'GET',
        path: `${BASE}/categories/{id}`,
        title: 'Show category',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'A single category.',
      },
      {
        method: 'POST',
        path: `${BASE}/categories`,
        title: 'Create category',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Create a category.',
        body: [
          { name: 'name', type: 'string', required: true, description: 'Category name.' },
          { name: 'description', type: 'string', description: 'Optional.' },
          { name: 'status', type: 'string', description: 'active or inactive.' },
        ],
      },
      {
        method: 'PUT',
        path: `${BASE}/categories/{id}`,
        title: 'Update category',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Update a category.',
      },
      {
        method: 'PATCH',
        path: `${BASE}/categories/{id}/toggle-status`,
        title: 'Toggle category status',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Flip a category between active and inactive.',
      },
      {
        method: 'DELETE',
        path: `${BASE}/categories/{id}`,
        title: 'Delete category',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Hard-delete a category.',
        errors: ['403 — not an admin'],
      },
    ],
  },
  {
    id: 'suppliers',
    title: 'Suppliers',
    description: 'Companies you purchase goods from, referenced by products and purchase orders.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/suppliers`,
        title: 'List suppliers',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated suppliers with search and status filters.',
      },
      {
        method: 'GET',
        path: `${BASE}/suppliers/{id}`,
        title: 'Show supplier',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'A single supplier.',
      },
      {
        method: 'POST',
        path: `${BASE}/suppliers`,
        title: 'Create supplier',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Create a supplier.',
        body: [
          { name: 'name', type: 'string', required: true, description: 'Supplier name.' },
          { name: 'email', type: 'email', required: true, description: 'Must be unique.' },
          { name: 'phone', type: 'string', required: true, description: 'Contact phone.' },
          { name: 'company', type: 'string', description: 'Company name.' },
          { name: 'contact_person', type: 'string', description: 'Contact person.' },
          { name: 'address', type: 'string', description: 'Optional.' },
          { name: 'status', type: 'string', description: 'active or inactive.' },
        ],
      },
      {
        method: 'PUT',
        path: `${BASE}/suppliers/{id}`,
        title: 'Update supplier',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Update a supplier.',
      },
      {
        method: 'DELETE',
        path: `${BASE}/suppliers/{id}`,
        title: 'Delete supplier',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Delete a supplier.',
        errors: ['403 — not an admin'],
      },
    ],
  },
  {
    id: 'customers',
    title: 'Customers',
    description: 'People and companies you sell to, referenced by sales orders.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/customers`,
        title: 'List customers',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated customers with search and status filters.',
      },
      {
        method: 'GET',
        path: `${BASE}/customers/all`,
        title: 'All active customers',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Unpaginated list of active customers (used in forms).',
      },
      {
        method: 'GET',
        path: `${BASE}/customers/{id}`,
        title: 'Show customer',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'A single customer.',
      },
      {
        method: 'POST',
        path: `${BASE}/customers`,
        title: 'Create customer',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Create a customer.',
        body: [
          { name: 'name', type: 'string', required: true, description: 'Customer name.' },
          { name: 'email', type: 'email', description: 'Optional.' },
          { name: 'phone', type: 'string', description: 'Optional.' },
          { name: 'address', type: 'string', description: 'Optional.' },
          { name: 'status', type: 'string', description: 'active or inactive.' },
        ],
      },
      {
        method: 'PUT',
        path: `${BASE}/customers/{id}`,
        title: 'Update customer',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Update a customer.',
      },
      {
        method: 'DELETE',
        path: `${BASE}/customers/{id}`,
        title: 'Delete customer',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Delete a customer. Blocked when the customer has sales history.',
        errors: ['409 — cannot delete a customer with sales history'],
      },
    ],
  },
  {
    id: 'inventory',
    title: 'Inventory',
    description: 'Current stock levels, one row per product per warehouse. Stock can never go negative.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/inventory`,
        title: 'List inventory',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated inventory rows with warehouse and product filters. Pass ?low_stock=true to filter.',
        params: ['warehouse_id', 'product_id', 'low_stock — true', 'page, per_page (1–100)'],
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/inventory/low-stock`,
        title: 'Low stock inventory',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Inventory rows at or below reorder point.',
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/inventory/{id}`,
        title: 'Show inventory row',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'A single product/warehouse stock row.',
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'PUT',
        path: `${BASE}/inventory/{id}`,
        title: 'Adjust stock',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Manually set the quantity. Writes an adjustment ledger entry at the current average cost.',
        body: [
          { name: 'quantity', type: 'integer', required: true, description: 'New quantity (min 0).' },
          { name: 'reason', type: 'string', required: true, description: 'Why the adjustment was made.' },
        ],
        managerScope: 'Managers can adjust only their assigned warehouse.',
        errors: ['422 — archived warehouse or archived product', '422 — insufficient available stock'],
      },
      {
        method: 'POST',
        path: `${BASE}/inventory/transfer`,
        title: 'Transfer stock',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Move stock between two active warehouses. Two ledger entries are written; WAC is unchanged.',
        body: [
          { name: 'product_id', type: 'number', required: true, description: 'Product to move.' },
          { name: 'from_warehouse_id', type: 'number', required: true, description: 'Source warehouse.' },
          { name: 'to_warehouse_id', type: 'number', required: true, description: 'Destination warehouse (different from source).' },
          { name: 'quantity', type: 'integer', required: true, description: 'Units to move (min 1).' },
          { name: 'notes', type: 'string', description: 'Optional note.' },
        ],
        managerScope: 'Managers can transfer only out of their assigned warehouse.',
        errors: ['422 — insufficient stock in source warehouse', '422 — inactive or archived warehouse'],
      },
      {
        method: 'POST',
        path: `${BASE}/inventory/{inventory}/write-off`,
        title: 'Write off stock',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Write off damaged or expired units. WAC is not changed.',
        body: [
          { name: 'type', type: 'string', required: true, description: 'damage or expired.' },
          { name: 'quantity', type: 'integer', required: true, description: 'Units to write off (min 1).' },
          { name: 'reason', type: 'string', required: true, description: 'Explanation (max 500 chars).' },
        ],
        managerScope: 'Managers can write off only their assigned warehouse.',
        errors: ['422 — insufficient available stock', '422 — archived warehouse or archived product'],
      },
    ],
  },
  {
    id: 'transactions',
    title: 'Transactions',
    description: 'The append-only inventory ledger. Transactions are never edited or deleted.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/transactions`,
        title: 'List transactions',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated ledger with warehouse, type, and date filters.',
        params: ['warehouse_id', 'type — purchase, sale, transfer, adjustment, return, return_in, damage, expired', 'date_from, date_to — YYYY-MM-DD'],
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/transactions/{id}`,
        title: 'Show transaction',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'A single ledger entry.',
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'POST',
        path: `${BASE}/transactions`,
        title: 'Record transaction',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Manually record a ledger entry. A positive purchase recalculates WAC.',
        body: [
          { name: 'product_id', type: 'number', required: true, description: 'Product involved.' },
          { name: 'warehouse_id', type: 'number', required: true, description: 'Warehouse involved (must not be archived).' },
          { name: 'type', type: 'string', required: true, description: 'purchase, sale, transfer, adjustment, return, damage, expired.' },
          { name: 'quantity', type: 'integer', required: true, description: 'Positive or negative (not 0).' },
          { name: 'unit_cost', type: 'number', description: 'Overrides the cost; otherwise the average cost is used.' },
          { name: 'reference_number', type: 'string', description: 'Reference such as an order number.' },
          { name: 'notes', type: 'string', description: 'Optional note.' },
        ],
        managerScope: 'Managers can record only against their assigned warehouse.',
        errors: ['422 — insufficient available stock', '422 — archived product for damage/expired/adjustment'],
      },
    ],
  },
  {
    id: 'purchase-orders',
    title: 'Purchase Orders',
    description: 'Orders placed with suppliers. Support partial receiving with received and remaining totals.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/purchase-orders`,
        title: 'List purchase orders',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated POs with supplier, warehouse, and status filters.',
        params: ['supplier_id', 'warehouse_id', 'status — draft, sent, partial, received, cancelled', 'date_from, date_to'],
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/purchase-orders/{id}`,
        title: 'Show purchase order',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'A PO with its items, totals, received amount, and remaining amount.',
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'POST',
        path: `${BASE}/purchase-orders`,
        title: 'Create purchase order',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Create a PO with line items.',
        body: [
          { name: 'supplier_id', type: 'number', required: true, description: 'Supplier.' },
          { name: 'warehouse_id', type: 'number', description: 'Receiving warehouse.' },
          { name: 'order_date', type: 'date', description: 'Defaults to today.' },
          { name: 'expected_date', type: 'date', description: 'Expected arrival.' },
          { name: 'notes', type: 'string', description: 'Optional.' },
          { name: 'items', type: 'array', required: true, description: 'Line items with product_id, quantity_ordered, unit_cost.' },
        ],
        managerScope: 'Managers must be assigned to a warehouse (403 otherwise).',
        errors: ['403 — manager is not assigned to a warehouse', '422 — validation failed'],
      },
      {
        method: 'PUT',
        path: `${BASE}/purchase-orders/{id}`,
        title: 'Update purchase order',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Update PO details and line items.',
        managerScope: 'Managers can update only their assigned warehouse POs.',
      },
      {
        method: 'PATCH',
        path: `${BASE}/purchase-orders/{id}/status`,
        title: 'Update PO status',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Move a PO through its status machine (draft → sent → partial → received).',
        body: [
          { name: 'status', type: 'string', required: true, description: 'Next allowed status.' },
        ],
        errors: ['422 — illegal status transition'],
      },
      {
        method: 'POST',
        path: `${BASE}/purchase-orders/{id}/receive`,
        title: 'Receive goods',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Receive all or part of a PO. Stock increases, WAC recalculates, and the PO becomes partial or received.',
        body: [
          { name: 'warehouse_id', type: 'number', description: 'Receiving warehouse; defaults to the PO warehouse.' },
          { name: 'items', type: 'array', required: true, description: 'purchase_order_item_id and quantity_received.' },
        ],
        managerScope: 'Managers must be authorized for the PO and receiving warehouses.',
        errors: [
          '422 — quantity received exceeds remaining units',
          '422 — cannot receive onto a cancelled or received PO',
          '422 — archived or inactive receiving warehouse',
          '422 — items do not belong to this PO',
        ],
      },
      {
        method: 'DELETE',
        path: `${BASE}/purchase-orders/{id}`,
        title: 'Delete purchase order',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Delete a PO.',
        errors: ['403 — not an admin'],
      },
    ],
  },
  {
    id: 'sales-orders',
    title: 'Sales Orders',
    description: 'Orders placed by customers. Move from draft → confirmed → shipped.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/sales-orders`,
        title: 'List sales orders',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated SOs with customer, warehouse, and status filters.',
        params: ['customer_id', 'warehouse_id', 'status — draft, confirmed, shipped, cancelled', 'date_from, date_to'],
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/sales-orders/{id}`,
        title: 'Show sales order',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'An SO with its items and totals.',
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/sales-orders/{id}/returnable`,
        title: 'Returnable items',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Shipped lines of an SO with already-returned and returnable quantities.',
      },
      {
        method: 'POST',
        path: `${BASE}/sales-orders`,
        title: 'Create sales order',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Create an SO with line items.',
        body: [
          { name: 'customer_id', type: 'number', required: true, description: 'Customer.' },
          { name: 'warehouse_id', type: 'number', required: true, description: 'Fulfilment warehouse.' },
          { name: 'order_date', type: 'date', description: 'Defaults to today.' },
          { name: 'notes', type: 'string', description: 'Optional.' },
          { name: 'items', type: 'array', required: true, description: 'Line items with product_id and quantity.' },
        ],
        managerScope: 'Managers must be assigned to a warehouse (403 otherwise).',
      },
      {
        method: 'PUT',
        path: `${BASE}/sales-orders/{id}`,
        title: 'Update sales order',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Update an SO. Only draft orders can be edited.',
        errors: ['422 — only draft sales orders can be edited'],
      },
      {
        method: 'POST',
        path: `${BASE}/sales-orders/{id}/confirm`,
        title: 'Confirm sales order',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Confirm a draft order. Validates the customer, warehouse, and products are active.',
        errors: ['422 — only draft orders can be confirmed', '422 — customer/warehouse/product not active or no items'],
      },
      {
        method: 'POST',
        path: `${BASE}/sales-orders/{id}/ship`,
        title: 'Ship sales order',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Ship a confirmed order. Validates stock and snapshots WAC for COGS.',
        errors: ['422 — insufficient stock for product', '422 — only confirmed orders can be shipped', '409 — already shipped'],
      },
      {
        method: 'POST',
        path: `${BASE}/sales-orders/{id}/cancel`,
        title: 'Cancel sales order',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Cancel a draft or confirmed order.',
        errors: ['422 — only draft or confirmed orders can be cancelled'],
      },
      {
        method: 'DELETE',
        path: `${BASE}/sales-orders/{id}`,
        title: 'Delete sales order',
        auth: AUTH_TOKEN,
        roles: ADMIN_ONLY,
        description: 'Delete a draft or cancelled SO.',
        errors: ['403 — not an admin', '422 — only draft or cancelled orders can be deleted'],
      },
    ],
  },
  {
    id: 'returns',
    title: 'Returns',
    description: 'Customer returns against shipped sales orders. Completing a return restores stock and reverses revenue/COGS.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/customer-returns`,
        title: 'List returns',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'Paginated returns with customer, warehouse, and status filters.',
        params: ['customer_id', 'warehouse_id', 'status — draft, completed, cancelled', 'date_from, date_to'],
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/customer-returns/{id}`,
        title: 'Show return',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'A return with its items.',
        managerScope: 'Managers see only their assigned warehouse.',
      },
      {
        method: 'POST',
        path: `${BASE}/customer-returns`,
        title: 'Create return',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Create a draft return against a shipped sales order.',
        body: [
          { name: 'sales_order_id', type: 'number', required: true, description: 'Shipped sales order.' },
          { name: 'warehouse_id', type: 'number', required: true, description: 'Warehouse receiving the goods.' },
          { name: 'return_date', type: 'date', description: 'Defaults to today.' },
          { name: 'reason', type: 'string', description: 'Optional.' },
          { name: 'items', type: 'array', required: true, description: 'sales_order_item_id and quantity.' },
        ],
        errors: ['422 — only shipped orders can have returned items'],
      },
      {
        method: 'PUT',
        path: `${BASE}/customer-returns/{id}`,
        title: 'Update return',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Edit a draft return.',
      },
      {
        method: 'POST',
        path: `${BASE}/customer-returns/{id}/complete`,
        title: 'Complete return',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Restore stock and record return_in ledger entries carrying the original sale snapshot.',
        errors: [
          '422 — return quantity exceeds remaining returnable quantity',
          '422 — sales order warehouse archived or inactive',
          '422 — only draft returns can be completed',
        ],
      },
      {
        method: 'POST',
        path: `${BASE}/customer-returns/{id}/cancel`,
        title: 'Cancel return',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Cancel a draft return. Cancelled returns never touch stock.',
        errors: ['422 — only draft returns can be cancelled'],
      },
    ],
  },
  {
    id: 'reports',
    title: 'Reports',
    description: 'Financial and operational reports. Cost and profit data is restricted to admins and managers.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/reports/sales`,
        title: 'Sales report',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Summary plus per-sale rows with revenue, COGS, and gross profit.',
        params: ['date_from, date_to', 'customer_id', 'warehouse_id'],
        managerScope: 'Managers are scoped to their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/reports/profit`,
        title: 'Profit report',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Net sales, COGS, gross profit, and margin with daily and monthly breakdowns.',
        params: ['date_from, date_to', 'customer_id', 'warehouse_id'],
        managerScope: 'Managers are scoped to their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/reports/inventory-valuation`,
        title: 'Inventory valuation',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Current on-hand value using quantity × WAC, grouped by warehouse.',
        params: ['warehouse_id', 'category_id', 'product_id'],
        managerScope: 'Managers are scoped to their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/reports/write-off`,
        title: 'Write-off report',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Damage and expired stock with quantity and value at write-off cost.',
        params: ['type — damage, expired', 'date_from, date_to', 'warehouse_id'],
        managerScope: 'Managers are scoped to their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/reports/returns`,
        title: 'Returns report',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Completed returns with units, value, and COGS.',
        params: ['date_from, date_to', 'customer_id', 'warehouse_id'],
        managerScope: 'Managers are scoped to their assigned warehouse.',
      },
      {
        method: 'GET',
        path: `${BASE}/reports/financial-overview`,
        title: 'Financial overview',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description:
          'Purchase spend, current inventory value, sales, COGS, gross profit, write-off loss, and the result after write-offs.',
        params: ['date_from, date_to', 'warehouse_id', 'category_id', 'product_id'],
        managerScope: 'Managers are scoped to their assigned warehouse.',
      },
    ],
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Operational and financial summaries for the dashboard.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/dashboard/stats`,
        title: 'Dashboard stats',
        auth: AUTH_TOKEN,
        roles: ANY_ROLE,
        description: 'KPIs: low stock count, recent transactions, inventory value, top products, today and month financials, write-offs, returns, and last-30-days sales.',
        managerScope: 'Managers get stats scoped to their assigned warehouse.',
      },
    ],
  },
  {
    id: 'activity-logs',
    title: 'Activity Logs',
    description: 'The append-only audit trail of actions performed across the system.',
    endpoints: [
      {
        method: 'GET',
        path: `${BASE}/activity-logs`,
        title: 'List activity logs',
        auth: AUTH_TOKEN,
        roles: ADMIN_MANAGER,
        description: 'Paginated audit entries with user, action, model, and date filters.',
        params: ['user_id', 'action', 'model_type', 'model_id', 'search', 'date_from, date_to', 'page, per_page'],
        errors: ['403 — role not allowed'],
      },
    ],
  },
]